### ISSUE TITLE
How to ?

### ISSUE THREAD

**Issue by the-conqueror-97** [sonyxperiadev/device-sony-satsuki#54]
HI, i just would like to know how do you exactly build this rom. 
Can someone tell me where to git clone this repo ?
And how to build it then ?

OR

A simple tutorial to make it easy ?

I've already built lineage OS for this device.
But for some reason, i couldn't build AOSP for the Z5P by following the tutorial given on sony's developer site.
But i could build one for more recent devices like XZ Premium.

I'm under ubuntu 20.04 with all packages installed for building.

**Comment by jerpelea** [comment]
https://developer.sony.com/develop/open-devices/guides/aosp-build-instructions/
https://developer.sony.com/develop/open-devices/get-started/supported-devices-and-functionality
